-- 三端簡易叫車紀錄管理系統
-- 資料庫初始化腳本

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS Passengers (
  PassengerID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  乘客姓名 VARCHAR(50) NOT NULL,
  密碼 VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Drivers (
  DriverID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  駕駛姓名 VARCHAR(50) NOT NULL,
  密碼 VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Admins (
  AdminID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  帳號 VARCHAR(50) NOT NULL UNIQUE,
  密碼 VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Rides (
  RideID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PassengerID INT(11) NOT NULL,
  DriverID INT(11) DEFAULT NULL,
  起點 VARCHAR(255) NOT NULL,
  終點 VARCHAR(255) NOT NULL,
  預計乘車時間 DATETIME NOT NULL,
  預約建立時間 DATETIME DEFAULT current_timestamp(),
  FOREIGN KEY (PassengerID) REFERENCES Passengers(PassengerID),
  FOREIGN KEY (DriverID) REFERENCES Drivers(DriverID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Settlements (
  RideID INT(11) NOT NULL PRIMARY KEY,
  實際里程 DECIMAL(6,2) DEFAULT NULL,
  最終價格 DECIMAL(8,2) DEFAULT NULL,
  確認狀態 ENUM('待確認','已確認') DEFAULT '待確認',
  完成確認時間 DATETIME DEFAULT NULL,
  FOREIGN KEY (RideID) REFERENCES Rides(RideID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
